const countryData = [
    { code: "af", name: "Afghanistan", flag: "🇦🇫", dialCode: "+93" },
    { code: "al", name: "Albania", flag: "🇦🇱", dialCode: "+355" },
    { code: "dz", name: "Algeria", flag: "🇩🇿", dialCode: "+213" },
    { code: "as", name: "American Samoa", flag: "🇦🇸", dialCode: "+1" },
    { code: "ad", name: "Andorra", flag: "🇦🇩", dialCode: "+376" },
    { code: "ao", name: "Angola", flag: "🇦🇴", dialCode: "+244" },
    { code: "ai", name: "Anguilla", flag: "🇦🇮", dialCode: "+1" },
    { code: "ag", name: "Antigua and Barbuda", flag: "🇦🇬", dialCode: "+1" },
    { code: "ar", name: "Argentina", flag: "🇦🇷", dialCode: "+54" },
    { code: "am", name: "Armenia", flag: "🇦🇲", dialCode: "+374" },
    { code: "au", name: "Australia", flag: "🇦🇺", dialCode: "+61" },
    { code: "at", name: "Austria", flag: "🇦🇹", dialCode: "+43" },
    { code: "az", name: "Azerbaijan", flag: "🇦🇿", dialCode: "+994" },
    { code: "bh", name: "Bahrain", flag: "🇧🇭", dialCode: "+973" },
    { code: "bd", name: "Bangladesh", flag: "🇧🇩", dialCode: "+880" },
    { code: "bb", name: "Barbados", flag: "🇧🇧", dialCode: "+1" },
    { code: "by", name: "Belarus", flag: "🇧🇾", dialCode: "+375" },
    { code: "be", name: "Belgium", flag: "🇧🇪", dialCode: "+32" },
    { code: "bz", name: "Belize", flag: "🇧🇿", dialCode: "+501" },
    { code: "bj", name: "Benin", flag: "🇧🇯", dialCode: "+229" },
    { code: "bt", name: "Bhutan", flag: "🇧🇹", dialCode: "+975" },
    { code: "bo", name: "Bolivia", flag: "🇧🇴", dialCode: "+591" },
    { code: "br", name: "Brazil", flag: "🇧🇷", dialCode: "+55" },
    { code: "bg", name: "Bulgaria", flag: "🇧🇬", dialCode: "+359" },
    { code: "bf", name: "Burkina Faso", flag: "🇧🇫", dialCode: "+226" },
    { code: "bi", name: "Burundi", flag: "🇧🇮", dialCode: "+257" },
    { code: "kh", name: "Cambodia", flag: "🇰🇭", dialCode: "+855" },
    { code: "cm", name: "Cameroon", flag: "🇨🇲", dialCode: "+237" },
    { code: "ca", name: "Canada", flag: "🇨🇦", dialCode: "+1" },
    { code: "cv", name: "Cape Verde", flag: "🇨🇻", dialCode: "+238" },
    { code: "cf", name: "Central African Republic", flag: "🇨🇫", dialCode: "+236" },
    { code: "td", name: "Chad", flag: "🇹🇩", dialCode: "+235" },
    { code: "cl", name: "Chile", flag: "🇨🇱", dialCode: "+56" },
    { code: "cn", name: "China", flag: "🇨🇳", dialCode: "+86" },
    { code: "co", name: "Colombia", flag: "🇨🇴", dialCode: "+57" },
    { code: "km", name: "Comoros", flag: "🇰🇲", dialCode: "+269" },
    { code: "cd", name: "Congo (Democratic Republic)", flag: "🇨🇩", dialCode: "+243" },
    { code: "cg", name: "Congo (Republic)", flag: "🇨🇬", dialCode: "+242" },
    { code: "cr", name: "Costa Rica", flag: "🇨🇷", dialCode: "+506" },
    { code: "hr", name: "Croatia", flag: "🇭🇷", dialCode: "+385" },
    { code: "cu", name: "Cuba", flag: "🇨🇺", dialCode: "+53" },
    { code: "cy", name: "Cyprus", flag: "🇨🇾", dialCode: "+357" },
    { code: "cz", name: "Czech Republic", flag: "🇨🇿", dialCode: "+420" },
    { code: "dk", name: "Denmark", flag: "🇩🇰", dialCode: "+45" },
    { code: "dj", name: "Djibouti", flag: "🇩🇯", dialCode: "+253" },
    { code: "eg", name: "Egypt", flag: "🇪🇬", dialCode: "+20" },
    { code: "fr", name: "France", flag: "🇫🇷", dialCode: "+33" },
    { code: "de", name: "Germany", flag: "🇩🇪", dialCode: "+49" },
    { code: "in", name: "India", flag: "🇮🇳", dialCode: "+91" },
    { code: "id", name: "Indonesia", flag: "🇮🇩", dialCode: "+62" },
    { code: "it", name: "Italy", flag: "🇮🇹", dialCode: "+39" },
    { code: "jp", name: "Japan", flag: "🇯🇵", dialCode: "+81" },
    { code: "ke", name: "Kenya", flag: "🇰🇪", dialCode: "+254" },
    { code: "my", name: "Malaysia", flag: "🇲🇾", dialCode: "+60" },
    { code: "mx", name: "Mexico", flag: "🇲🇽", dialCode: "+52" },
    { code: "ru", name: "Russia", flag: "🇷🇺", dialCode: "+7" },
    { code: "za", name: "South Africa", flag: "🇿🇦", dialCode: "+27" },
    { code: "es", name: "Spain", flag: "🇪🇸", dialCode: "+34" },
    { code: "se", name: "Sweden", flag: "🇸🇪", dialCode: "+46" },
    { code: "ch", name: "Switzerland", flag: "🇨🇭", dialCode: "+41" },
    { code: "tr", name: "Turkey", flag: "🇹🇷", dialCode: "+90" },
    { code: "ua", name: "Ukraine", flag: "🇺🇦", dialCode: "+380" },
    { code: "ae", name: "United Arab Emirates", flag: "🇦🇪", dialCode: "+971" },
    { code: "gb", name: "United Kingdom", flag: "🇬🇧", dialCode: "+44" },
    { code: "us", name: "United States", flag: "🇺🇸", dialCode: "+1" },
    { code: "vn", name: "Vietnam", flag: "🇻🇳", dialCode: "+84" }
  ];

export default countryData;